---
- hosts: tag_Name_asg_ec2
  connection: ssh
  become: true
  tasks:
  - name: installing apache2 server
    apt:
        name: apache2
        update_cache: true
        state: present

  - name: create the webpage index.html
    copy:
        src: /home/ubuntu/apache/index.html
        dest: /var/www/html/index.html

  - name: start apache
    service:
        name: apache2
        state: started